function text = defaultSettingsText()
%DEFAULTSETTINGSTEXT Default plain-text settings template for the Noise Analyzer app (key=value
%   lines, '#' starts a comment). The same text can be typed directly into the app or saved/
%   loaded as a .txt config file -- both paths go through parseSettingsText.
text = sprintf([ ...
    '# Noise Analyzer settings -- edit here, or load/save as a .txt file\n' ...
    'SampleRateHz =\n' ...
    '# ^ leave blank to auto-detect from a time column in the loaded data file\n' ...
    'ReferencePressurePa = 2e-5\n' ...
    'TimeWeighting = Fast\n' ...
    '# TimeWeighting: Fast or Slow\n' ...
    ]);
end
